#page title
page_title: KeyTrails Keystroke Presenter # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id: 1612708557 # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country: us # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link: https://apps.apple.com/app/scaler-bandwidth-monitor/id1612708557?mt=12 # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link: # Enter Google Play Store URL.
presskit_download_link:
  https://faisalbin.com # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
  # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon: assets/appicon.png # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name: KeyTrails # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price: Free # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description: Present your keypresses on screen in style.

enable_smart_app_banner: true # Set to true to show a smart app banner at top of page on mobile devices.

# Information About Yourself
your_name: Faisal Ahmed
your_link: https://faisalbin.com
your_city: Munich
email_address: dev@faisalbin.com
facebook_username:
instagram_username:
twitter_username: faisalbahmed
github_username: faisalbinahmed
youtube_username:

# Feature List                            Edit, add or remove features to be presented.
features:
  - title: Visualize
    description: Visualize your keypresses in style.
    fontawesome_icon_name: keyboard-o

  - title: Customize
    description: Personalize the look of the keys.
    fontawesome_icon_name: magic

  - title: Native
    description: Universal App support. (works with Native M1 macOS devices)
    fontawesome_icon_name: palette

  - title: Similarity
    description: Keys look and feel just like your physical device.
    fontawesome_icon_name: fire

  - title: Control
    description: Limit number of keys and their lifetime on screen.
    fontawesome_icon_name: tools

  - title: Clicks
    description: Optionally visualize mouse clicks as well.
    fontawesome_icon_name: mouse-pointer

  - title: Placement
    description: Position it anywhere on screen, on any screen.
    fontawesome_icon_name: arrows
# Feature List                            Edit, add or remove features to be presented.
# features:
#   - title: Realtime monitoring of your system's download and upload speed from Menubar.
#     description: " " # New Feature Description
#     fontawesome_icon_name: magic

#   - title: Chart overview of the recent network speeds.
#     description: " " # New Feature Description
#     fontawesome_icon_name: magic

#   - title: Universal App support. (works with Native M1 macOS devices)
#     description: " " # New Feature Description
#     fontawesome_icon_name: magic

#   - title: Customizations - tweak how the Menubar data looks by modifying visible speed type, its unit, number of lines, and color.
#     description: " " # New Feature Description
#     fontawesome_icon_name: magic # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.

#    - title:  Pause or Resume the app anytime.
#     description: " "# Designed for GitHub Pages. Fork. Edit _config.yml. Upload screenshot/video. Push to gh-pages branch. Voilá!
#     fontawesome_icon_name: magic

# Theme Settings
topbar_color: "#000000"
topbar_transparency: 0.1
topbar_title_color: "#ffffff"

cover_image: assets/headerimage.png # Replace with alternative image path or image URL.
cover_overlay_color: "#363b3d"
cover_overlay_transparency: 0.8

device_color: black # Set to: blue, black, yellow, coral or white.

body_background_color: "#ffffff"

link_color: "#1d63ea"

app_title_color: "#ffffff"
app_price_color: "#ffffff"
app_description_color: "#ffffff"

feature_title_color: "#000000"
feature_text_color: "#666666"

feature_icons_foreground_color: "#1d63ea"
feature_icons_background_color: "#e6e6e6"

social_icons_foreground_color: "#666666"
social_icons_background_color: "#e6e6e6"

footer_text_color: "#666666"

####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
